export const TOPUP_STATE = Object.freeze({
  PAYMENT_QUEUED: 'PAYMENT_QUEUED',
  PROCESSING: 'PROCESSING',
  REDEEMED: 'REDEEMED',
  CREDITED: 'CREDITED',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
  FAILED: 'FAILED',
  REVERSED: 'REVERSED',
});

export const TOPUP_TRANSITIONS = Object.freeze({
  PAYMENT_QUEUED: ['PROCESSING'],
  PROCESSING: ['REDEEMED', 'MANUAL_REVIEW', 'FAILED'],
  MANUAL_REVIEW: ['REDEEMED', 'CREDITED', 'FAILED'],
  REDEEMED: ['CREDITED', 'MANUAL_REVIEW'],
  CREDITED: ['REVERSED'],
  FAILED: [],
  REVERSED: [],
});
