export const ORDER_ITEM_STATE = Object.freeze({
  SELECTED: 'SELECTED',
  RESERVED: 'RESERVED',
  QUEUED: 'QUEUED',
  LEASED: 'LEASED',
  RUNNING: 'RUNNING',
  VERIFYING: 'VERIFYING',
  WAITING_RATE_LIMIT: 'WAITING_RATE_LIMIT',
  WAITING_RETRY: 'WAITING_RETRY',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
  SETTLING: 'SETTLING',
  READY_TO_CLAIM: 'READY_TO_CLAIM',
  EXPIRED_RELEASED: 'EXPIRED_RELEASED',
  EXTERNAL_COMPLETED_RELEASED: 'EXTERNAL_COMPLETED_RELEASED',
  STOPPED_RELEASED: 'STOPPED_RELEASED',
  FAILED_RELEASED: 'FAILED_RELEASED',
});

export const RELEASED_STATES = Object.freeze([
  ORDER_ITEM_STATE.EXPIRED_RELEASED,
  ORDER_ITEM_STATE.EXTERNAL_COMPLETED_RELEASED,
  ORDER_ITEM_STATE.STOPPED_RELEASED,
  ORDER_ITEM_STATE.FAILED_RELEASED,
]);

export const TERMINAL_ITEM_STATES = Object.freeze([
  ORDER_ITEM_STATE.READY_TO_CLAIM,
  ...RELEASED_STATES,
]);

export const ORDER_ITEM_TRANSITIONS = Object.freeze({
  SELECTED: ['RESERVED'],
  RESERVED: ['QUEUED', 'EXPIRED_RELEASED', 'EXTERNAL_COMPLETED_RELEASED', 'STOPPED_RELEASED', 'MANUAL_REVIEW'],
  QUEUED: ['LEASED', 'EXPIRED_RELEASED', 'EXTERNAL_COMPLETED_RELEASED', 'STOPPED_RELEASED', 'MANUAL_REVIEW'],
  LEASED: ['RUNNING', 'QUEUED', 'WAITING_RATE_LIMIT', 'EXPIRED_RELEASED', 'EXTERNAL_COMPLETED_RELEASED', 'STOPPED_RELEASED', 'MANUAL_REVIEW'],
  RUNNING: ['VERIFYING', 'WAITING_RATE_LIMIT', 'WAITING_RETRY', 'FAILED_RELEASED', 'MANUAL_REVIEW'],
  VERIFYING: ['SETTLING', 'WAITING_RETRY', 'FAILED_RELEASED', 'MANUAL_REVIEW'],
  WAITING_RATE_LIMIT: ['QUEUED', 'RUNNING', 'FAILED_RELEASED', 'MANUAL_REVIEW'],
  WAITING_RETRY: ['QUEUED', 'RUNNING', 'FAILED_RELEASED', 'MANUAL_REVIEW'],
  MANUAL_REVIEW: ['QUEUED', 'SETTLING', 'EXPIRED_RELEASED', 'EXTERNAL_COMPLETED_RELEASED', 'STOPPED_RELEASED', 'FAILED_RELEASED'],
  SETTLING: ['READY_TO_CLAIM', 'FAILED_RELEASED', 'MANUAL_REVIEW'],
  READY_TO_CLAIM: [],
  EXPIRED_RELEASED: [],
  EXTERNAL_COMPLETED_RELEASED: [],
  STOPPED_RELEASED: [],
  FAILED_RELEASED: [],
});
